version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
#    command: [ "./api" ]
    environment:
      - PORT=9500
      - DATABASE_URL=postgres://postgres:password@busha_db:5432/busha
      - REDISCLOUD_URL=redis://redis:6379
      - HOST_MACHINE=localhost:9500
    container_name: api
    ports:
      - 9500:9500
    volumes:
        - .:/app
    depends_on:
      - redis
      - db
    networks:
      - default

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - default

  db:
    image: postgres:13-alpine
    container_name: busha_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "busha"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - default

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    environment:
      - HOST_MACHINE=api:9500
    depends_on:
      - api

networks:
  default:
