version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
#    command: [ "./api" ]
    environment:
      PORT: "9500"
      POSTGRES_URL: "postgres://postgres:password@busha_db:5432/busha"
      REDIS_URL: redis://busha_redis:6380
    container_name: api
    ports:
      - 9500:9500
    volumes:
        - .:/app
    depends_on:
      - busha_redis
      - db
    networks:
      - default

  busha_redis:
    image: redis:5-alpine
    container_name: busha_redis
    ports:
      - 6380:6379
    restart: always
    networks:
      - default

  db:
    image: postgres:13-alpine
    container_name: busha_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "busha"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - default

networks:
  default:
