definitions:
  model.AddCommentRequest:
    properties:
      message:
        type: string
    type: object
  model.CharacterList:
    properties:
      characters:
        items:
          $ref: '#/definitions/model.CharacterList_Character'
        type: array
      total_cm:
        type: integer
      total_count:
        type: integer
      total_ft:
        type: string
      total_in:
        type: number
    type: object
  model.CharacterList_Character:
    properties:
      gender:
        type: string
      height_cm:
        type: integer
      height_ft:
        type: string
      height_in:
        type: number
      name:
        type: string
    type: object
  model.Comment:
    properties:
      id:
        type: string
      message:
        type: string
      movie_id:
        type: integer
      updated_at:
        type: string
    type: object
  model.GenericResponse:
    properties:
      code:
        example: 200
        type: integer
      count:
        example: 10
        type: integer
      data:
        type: object
      error:
        type: object
      message:
        example: success
        type: string
    type: object
  model.Movie:
    properties:
      comment_count:
        example: 10
        type: integer
      id:
        example: 1
        type: integer
      name:
        example: A New Hope
        type: string
      opening_crawl:
        example: It is a period of civil war. Rebel spaceships, striking from a hidden
          base, have won their first victory against the evil Galactic Empire.
        type: string
      release_date:
        example: "1977-05-25"
        type: string
    type: object
info:
  contact:
    email: natorverinumbe@gmail.com
    name: Nator Verinumbe
  description: This documents all rest endpoints exposed by this application.
  title: Busha Movie API documentation
  version: 1.0.0
paths:
  /characters/{movie_id}:
    get:
      description: Get all characters in a movie
      parameters:
      - description: Movie ID
        in: path
        name: movie_id
        required: true
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: pageSize
        type: integer
      - description: Sort key (name | gender | height)
        in: query
        name: sortKey
        type: string
      - description: Sort order (asc | desc)
        in: query
        name: sortOrder
        type: string
      - description: ' '' Gender (female'' | ''male'')'
        in: query
        name: gender
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.CharacterList'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                error:
                  type: string
              type: object
        "502":
          description: Bad Gateway
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get all characters in a movie
      tags:
      - Characters
  /comments/{movie_id}:
    get:
      description: Get all comments for a movie
      parameters:
      - description: Movie ID
        in: path
        name: movie_id
        required: true
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                ' count':
                  type: integer
                ' message':
                  type: string
                data:
                  items:
                    $ref: '#/definitions/model.Comment'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                error:
                  type: string
              type: object
        "502":
          description: Bad Gateway
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get all comments for a movie
      tags:
      - Comments
    post:
      consumes:
      - application/json
      description: Add a comment to a movie
      parameters:
      - description: Movie ID
        in: path
        name: movie_id
        required: true
        type: integer
      - description: Comment
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/model.AddCommentRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                message:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                error:
                  type: string
              type: object
        "502":
          description: Bad Gateway
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Add a comment to a movie
      tags:
      - Comments
  /movies:
    get:
      description: Get all movies
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                ' count':
                  type: integer
                ' message':
                  type: string
                data:
                  items:
                    $ref: '#/definitions/model.Movie'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                ' message':
                  type: string
                error:
                  type: string
              type: object
        "502":
          description: Bad Gateway
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                ' message':
                  type: string
                error:
                  type: string
              type: object
      summary: Get all movies
      tags:
      - Movies
  /movies/{movie_id}:
    get:
      description: Get a movie
      parameters:
      - description: Movie ID
        in: path
        name: movie_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.Movie'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                error:
                  type: string
              type: object
        "502":
          description: Bad Gateway
          schema:
            allOf:
            - $ref: '#/definitions/model.GenericResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get a movie
      tags:
      - Movies
swagger: "2.0"
